#!/bin/sh

if [ -f "/var/mobile/Library/Preferences/com.fahlnbg.appcheats.plist" ];then
    rm -rf "/var/mobile/Library/Preferences/com.fahlnbg.appcheats.plist"
    fi
echo
echo
echo ====================
echo App Cheats bởi Ttjb Team
echo ====================
echo
sleep 3