include $(THEOS)/makefiles/common.mk

TWEAK_NAME = FxxkHapticTouch
FxxkHapticTouch_FILES = a.xm
FxxkHapticTouch_LIBRARIES = MobileGestalt
FxxkHapticTouch_CFLAGS = -fobjc-arc
ARCHS = arm64 arm64e

include $(THEOS_MAKE_PATH)/tweak.mk
